name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.cyberzone.dev
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Get latest commit short SHA
      id: sha
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

    - name: Build and Push Container Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./containerfile
        push: true
        tags: |
          registry.cyberzone.dev/bots/vk-ds:${{ steps.sha.outputs.sha }}
          registry.cyberzone.dev/bots/vk-ds:latest